unbound:
    build: unbound
    hostname: unbound
    dns: 127.0.0.1
    links:
      - nsd
    volumes:
      - "./unbound-local.conf:/unbound-local.conf:ro"
nsd:
    build: nsd
    hostname: nsd
    volumes:
      - "./zones:/zones"
      - "./nsd-local.conf:/etc/nsd/nsd-local.conf:ro"
